export const namedRoutes = {
  home: 'home',
  members: 'members',
  schedule: 'schedule',
  playlists: 'playlists',
  notices: 'notices',
  testimonials: 'testimonials',
  church: 'church',
  requests: 'requests',
  pray: 'pray',
  videos: 'videos',
  login: 'login',
  privacyPolicy: 'privacy-policy',
  membersReports: 'members/reports',
} as const;
