export const namedRoutes = {
  home: 'home',
  members: 'members',
  schedule: 'schedule',
  scale: 'scale',
  playlists: 'playlists',
  notices: 'notices',
  positions: 'positions',
  testimonials: 'testimonials',
  church: 'church',
  requests: 'requests',
  pray: 'pray',
  videos: 'videos',
  ebd: { home: 'ebd', classes: 'classes' },
  login: 'login',
  privacyPolicy: 'privacy-policy',
  membersReports: 'members/reports',
  landing: 'sobre',
} as const;
